#!/bin/bash
# use the following to run in background: nohup ./chain_jobs.sh &
sbatch --partition cpu_il svat_crop_bretten_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bretten_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_bruchsal-heidelsheim_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_bare-grass_slurm.sh

sbatch --partition cpu_il svat_crop_ehingen-kirchen_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_ehingen-kirchen_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_eppingen-elsenz_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_grain-corn_winter-wheat_clover_slurm.sh

sbatch --partition cpu_il svat_crop_freiburg_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_freiburg_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_gottmadingen_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_grain-corn_winter-wheat_winter-barley_slurm.sh

sbatch --partition cpu_il svat_crop_hayingen_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_hayingen_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_kupferzell_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_grain-corn_winter-wheat_winter-rape_slurm.sh
# 
sbatch --partition cpu_il svat_crop_lahr_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_lahr_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_merklingen_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh

sbatch --partition cpu_il svat_crop_muellheim_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_muellheim_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_oehringen_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh

sbatch --partition cpu_il svat_crop_stockach_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_stockach_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_miscanthus_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_vellberg-kleinaltdorf_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_bare-grass_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_grain-corn_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_grain-corn_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_grain-corn_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_grain-corn_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_grain-corn_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_miscanthus_slurm.sh

sbatch --partition cpu_il svat_crop_weingarten_sugar-beet_winter-wheat_winter-barley_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_sugar-beet_winter-wheat_winter-barley_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_clover_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_winter-rape_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_summer-wheat_winter-wheat_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_clover_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_clover_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_soybean_winter-rape_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_sugar-beet_silage-corn_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_sugar-beet_silage-corn_yellow-mustard_slurm.sh
sbatch --partition cpu_il svat_crop_weingarten_winter-wheat_winter-rape_slurm.sh
