name: roger-mpi

channels:
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - click
    - entrypoints
    - requests
    - numpy
    - scipy
    - pandas
    - ruamel.yaml
    - pillow
    - loguru
    - tqdm
    - cython
    # - pip:
    #     - -e .
