name: roger-gpu

channels:
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - click
    - entrypoints
    - numpy
    - scipy
    - pandas
    - loguru
    - tqdm
    - cython
    # - pip:
    #     - -e .
