name: roger-mpi

channels:
    - conda-forge

dependencies:
    - python=3.10
    - pip
    - click
    - pyyaml
    - entrypoints
    - numpy
    - scipy
    - pandas
    - loguru
    - tqdm
    - cython
    - matplotlib
    - seaborn
    - cftime
