name: roger-gpu

channels:
    - conda-forge

dependencies:
    - python=3.12
    - pip
    - click
    - pyyaml
    - entrypoints
    - numpy
    - scipy
    - pandas
    - loguru
    - tqdm
    - cython
    - matplotlib
    - seaborn
    - cftime
    - bmipy