name: roger-mpi

channels:
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - click
    - pyyaml
    - entrypoints
    - numpy
    - scipy
    - pandas
    - loguru
    - tqdm
    - cython
    - pip:
        - diag-eff
