name: roger

channels:
    - conda-forge

dependencies:
    - python=3.10
    - pip
    - click
    - entrypoints
    - requests
    - numpy
    - scipy
    - pandas
    - ruamel.yaml
    - h5netcdf
    - h5py
    - pillow
    - loguru
    - tqdm
    - cython
    # extensions
    - spyder
    - seaborn
    - jaxlib
    - jax
    - mpi4py
    - mpi4jax
    - sphinx_rtd_theme
    - ipyparallel
    - xarray
    - cftime
    - salib
    # - pip:
    #     - -e .
