locations: 
- lahr
- bruchsal-heidelsheim
- pfullendorf
- nagold
- sachsenheim
- heidelberg
- mergentheim
- nagold
- grosserlach-mannenweiler
- wutoeschingen-ofteringen
- ulm
# - freiburg
# - rot-buch
# - elztal-rittersbach
# - ellwangen-rindelbach
# - klippeneck
# - hechingen
# - rheinau-memprechtshofen
# - muellheim
# - rheinstetten
# - weingarten
# - singen
# - altheim
# - stoetten
# - notzingen

irrigation_scenarios:
# - 20-ufc
# - 35-ufc
# - 50-ufc
- crop-specific

crop_rotation_scenarios:
- winter-wheat
- grain-corn
- grain-corn_winter-wheat_winter-rape
- grain-corn_winter-wheat_winter-rape_yellow-mustard
- summer-barley
- potato
- grain-corn_yellow-mustard
- winter-wheat_winter-rape
- winter-wheat_silage-corn
- winter-wheat_silage-corn_yellow-mustard
- winter-wheat_soybean_winter-rape
- silage-corn
- silage-corn_yellow-mustard
- summer-barley
- summer-barley_yellow-mustard
- clover
- winter-barley
- winter-rape
- faba-bean
- potato-early
- sugar-beet
- sugar-beet_yellow-mustard
- vegetables
- strawberry
- winter-wheat_clover
- summer-wheat_winter-wheat
# - summer-wheat_clover_winter-wheat
# - winter-wheat_clover_silage-corn
- winter-wheat_sugar-beet_silage-corn
- summer-wheat_winter-wheat_silage-corn
- summer-wheat_winter-wheat_winter-rape
- sugar-beet_winter-wheat_winter-barley
- grain-corn_winter-wheat_winter-barley
- grain-corn_winter-wheat_clover
- summer-wheat_winter-wheat_yellow-mustard
- winter-wheat_sugar-beet_silage-corn_yellow-mustard
- summer-wheat_winter-wheat_silage-corn_yellow-mustard
- summer-wheat_winter-wheat_winter-rape_yellow-mustard
- sugar-beet_winter-wheat_winter-barley_yellow-mustard
- grain-corn_winter-wheat_winter-barley_yellow-mustard
# - asparagus