#!/bin/bash
eval "$(conda shell.bash hook)"
conda activate roger
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario potato --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario clover --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location rot-buch --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location rot-buch
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario potato --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario clover --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location elztal-rittersbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location elztal-rittersbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario potato --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario clover --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location ellwangen-rindelbach --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location ellwangen-rindelbach
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario potato --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario clover --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location klippeneck --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location klippeneck
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario potato --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario clover --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location hechingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location hechingen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario potato --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario clover --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location rheinau-memprechtshofen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location rheinau-memprechtshofen
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario potato --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario clover --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location muellheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location muellheim
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario potato --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario clover --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location rheinstetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location rheinstetten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario potato --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario clover --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location weingarten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location weingarten
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario potato --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario clover --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location singen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location singen
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario potato --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario clover --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location altheim --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location altheim
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario potato --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario clover --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location stoetten --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location stoetten
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario potato --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_winter-rape --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_soybean_winter-rape --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario silage-corn_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-barley_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario clover --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-barley --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-rape --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario faba-bean --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario potato-early --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario vegetables --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario strawberry --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_clover --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_clover --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard --location notzingen
python svat_crop.py -b numpy -d cpu --location notzingen --irrigation-scenario crop-specific --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard --location notzingen
python merge_output.py
python write_simulations_to_csv.py