#!/bin/bash

sbatch -p compute svat_crop_rot-buch_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rot-buch_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_elztal-rittersbach_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_ellwangen-rindelbach_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_klippeneck_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_hechingen_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinau-memprechtshofen_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_muellheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_rheinstetten_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_weingarten_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_singen_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_altheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_stoetten_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_potato_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_soybean_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_faba-bean_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_potato-early_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_sugar-beet_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_sugar-beet_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_vegetables_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_strawberry_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_sugar-beet_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_silage-corn_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_winter-rape_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_sugar-beet_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_winter-wheat_winter-barley_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_winter-wheat_clover_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
sbatch -p compute svat_crop_notzingen_grain-corn_winter-wheat_winter-barley_yellow-mustard_crop-specific-irrigation.sh
