# --- Settings --------------------------------------------------------------
# name of the model run; is used to name the output files
identifier: ONEDEVENT
# spatial discretization in x-direction (in meters)
dx: 1
# spatial discretization in y-direction (in meters)
dy: 1
# origin of spatial grid
x_origin: 0
# origin of spatial grid
y_origin: 0

# --- Parameters ---------------------------------------------------------------
# land use ID (see README for description)
LU_ID: 8
# degree of sealing (-)
SEALING: 0
# surface slope (-)
SLOPE: 0.05
# total surface depression storage (mm)
S_DEP_TOT: 0
# soil depth (mm)
Z_SOIL: 1000
# density of vertical macropores (1/m2)
DMPV: 50
# density of horizontal macropores (1/m2)
DMPH: 300
# total length of vertical macropores (mm)
LMPV: 300
# air capacity (-)
THETA_AC: 0.1
# usable field capacity (-)
THETA_UFC: 0.1
# permanent wilting point (-)
THETA_PWP: 0.2
# saturated hydraulic conductivity (-)
KS: 9.2
# hydraulic conductivity of bedrock/saturated zone (-)
KF: 2500

# --- Initial conditions -------------------------------------------------------
# soil water content of root zone/upper soil layer (mm/h)
THETA_RZ: 0.3
# soil water content of subsoil/lower soil layer (mm/h)
THETA_SS: 0.3

# --- Diagnostics --------------------------------------------------------------
OUTPUT_RATE:
- "inf_mat"  # soil matrix infiltration (mm/day)
- "inf_mp"  # macropore infiltration (mm/day)
- "inf_sc"  # shrinkage crack infiltration (mm/day)
- "q_ss"  # percolation from subsoil (mm/day)
- "q_sub"  # lateral subsurface runoff (mm/day)
- "q_sub_mp"  # lateral macropore subsurface runoff (mm/day)
- "q_sub_mat"  # lateral matrix subsurface runoff (mm/day)
- "q_hof"  # hortonian surface runoff (mm/day)
- "q_sof"  # saturation surface runoff (mm/day)

# simulated hydrologic storages
OUTPUT_COLLECT:
- "theta"  # soil water content (-)
