#!/bin/bash

sbatch -p compute svat_crop_lahr_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_lahr_potato_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_lahr_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_lahr_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_clover_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_lahr_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_lahr_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_lahr_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_lahr_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_lahr_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_lahr_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_lahr_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_potato_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_clover_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_bruchsal-heidelsheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_potato_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_clover_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_pfullendorf_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_nagold_potato_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_nagold_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_nagold_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_clover_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_nagold_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_nagold_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_nagold_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_nagold_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_nagold_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_nagold_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_nagold_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_potato_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_clover_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_sachsenheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_potato_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_clover_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_heidelberg_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_potato_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_clover_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_mergentheim_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_potato_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_clover_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_grosserlach-mannenweiler_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_potato_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_clover_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_wutoeschingen-ofteringen_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_ulm_potato_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_ulm_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_ulm_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_clover_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_ulm_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_ulm_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_ulm_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_ulm_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_ulm_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_ulm_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_ulm_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_potato_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_soybean_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-barley_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_clover_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_faba-bean_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_potato-early_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_sugar-beet_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_sugar-beet_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_vegetables_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_strawberry_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_sugar-beet_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_silage-corn_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_winter-rape_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_sugar-beet_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_winter-wheat_winter-barley_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_winter-wheat_clover_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_winter-wheat_sugar-beet_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_silage-corn_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_summer-wheat_winter-wheat_winter-rape_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_sugar-beet_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
sbatch -p compute svat_crop_freiburg_grain-corn_winter-wheat_winter-barley_yellow-mustard_no-irrigation.sh
