irrigation_scenarios:
- 30-ufc
- 45-ufc
- 50-ufc
- 80-ufc
- crop-specific

crop_rotation_scenarios:
- winter-wheat_clover
- winter-wheat_silage-corn
- summer-wheat_winter-wheat
- summer-wheat_clover_winter-wheat
- winter-wheat_clover_silage-corn
- winter-wheat_sugar-beet_silage-corn
- summer-wheat_winter-wheat_silage-corn
- summer-wheat_winter-wheat_winter-rape
- winter-wheat_winter-rape
- winter-wheat_soybean_winter-rape
- sugar-beet_winter-wheat_winter-barley
- grain-corn_winter-wheat_winter-rape
- grain-corn_winter-wheat_winter-barley
- grain-corn_winter-wheat_clover
- winter-wheat_silage-corn_yellow-mustard
- summer-wheat_winter-wheat_yellow-mustard
- winter-wheat_sugar-beet_silage-corn_yellow-mustard
- summer-wheat_winter-wheat_silage-corn_yellow-mustard
- summer-wheat_winter-wheat_winter-rape_yellow-mustard
- sugar-beet_winter-wheat_winter-barley_yellow-mustard
- grain-corn_winter-wheat_winter-rape_yellow-mustard
- grain-corn_winter-wheat_winter-barley_yellow-mustard