#!/bin/bash
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_clover
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_silage-corn
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_clover_winter-wheat
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_clover_silage-corn
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_winter-rape
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_soybean_winter-rape
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_winter-wheat_winter-rape
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_winter-wheat_winter-barley
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_winter-wheat_clover
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_silage-corn_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario winter-wheat_sugar-beet_silage-corn_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat_silage-corn_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario summer-wheat_winter-wheat_winter-rape_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario sugar-beet_winter-wheat_winter-barley_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_winter-wheat_winter-rape_yellow-mustard
python svat_crop_nitrate.py -b numpy -d cpu --irrigation-scenario no_irrigation --crop-rotation-scenario grain-corn_winter-wheat_winter-barley_yellow-mustard
