# --- Settings --------------------------------------------------------------
# name of the model run; is used to name the output files
identifier: SVAT18O
# number of grid cells in x-direction
nx: 80
# number of grid cells in y-direction
ny: 53
# spatial discretization in x-direction (in meters)
dx: 25
# spatial discretization in y-direction (in meters)
dy: 25
# x-origin of spatial grid
x_origin: 412636.5
# y-origin of spatial grid
y_origin: 5310863.5
# number of substeps per timestep
SAS_SOLVER_SUBSTEPS: 6

# --- Parameters ---------------------------------------------------------------
SAS_SOLVER: 'deterministic'

# --- Initial conditions -------------------------------------------------------
# initial oxygen18 ration of soil water in root zone/upper soil layer (-)
d18O_RZ: -10
# initial oxygen18 ration of soil water in subsoil/lower soil layer (-)
d18O_SS: -10

# --- Diagnostics --------------------------------------------------------------
OUTPUT_FREQUENCY: 86400  # output frequency in seconds
OUTPUT_AVERAGE:
- "C_iso_in"
- "C_iso_transp"
- "C_iso_evap_soil"
- "C_iso_s"
- "C_iso_q_ss"
- "TT_transp"
- "TT_q_ss"
- "SA_s"
- "ttavg_transp"
- "tt10_transp"
- "tt50_transp"
- "tt90_transp"
- "ttavg_q_ss"
- "tt10_q_ss"
- "tt50_q_ss"
- "tt90_q_ss"
- "rtavg_s"
- "rt10_s"
- "rt50_s"
- "rt90_s"
