#!/bin/bash

sbatch -p gpu oneD_crop_base_soil-compaction.sh
sbatch -p gpu oneD_crop_base_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_base_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_base_yellow-mustard.sh
sbatch -p gpu oneD_crop_base_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude0_duration3_soil-compaction.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude0_duration3_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude0_duration3_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude0_duration3_yellow-mustard.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude0_duration3_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude2_duration3_soil-compaction.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude2_duration3_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude2_duration3_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude2_duration3_yellow-mustard.sh
sbatch -p gpu oneD_crop_spring-drought_magnitude2_duration3_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude0_duration3_soil-compaction.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude0_duration3_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude0_duration3_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude0_duration3_yellow-mustard.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude0_duration3_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude2_duration3_soil-compaction.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude2_duration3_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude2_duration3_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude2_duration3_yellow-mustard.sh
sbatch -p gpu oneD_crop_summer-drought_magnitude2_duration3_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_long-term_magnitude2_duration0_soil-compaction.sh
sbatch -p gpu oneD_crop_long-term_magnitude2_duration0_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_long-term_magnitude2_duration0_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_long-term_magnitude2_duration0_yellow-mustard.sh
sbatch -p gpu oneD_crop_long-term_magnitude2_duration0_soil-compaction_grain-corn-only.sh
sbatch -p gpu oneD_crop_base_2000-2024_soil-compaction.sh
sbatch -p gpu oneD_crop_base_2000-2024.sh
sbatch -p gpu oneD_crop_base_2000-2024_soil-compaction_irrigation.sh
sbatch -p gpu oneD_crop_base_2000-2024_soil-compaction_yellow-mustard.sh
sbatch -p gpu oneD_crop_base_2000-2024_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_base_2000-2024_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p gpu oneD_crop_base_2000-2024_soil-compaction_grain-corn-only.sh
