# --- Settings --------------------------------------------------------------
# name of the model run; is used to name the output files
identifier: ONED
# total grid numbers in y-direction
nx: 12
# total grid numbers in x-direction
ny: 24
# spatial discretization in x-direction (in meters)
dx: 1
# spatial discretization in y-direction (in meters)
dy: 1
# origin of spatial grid
x_origin: 0
# origin of spatial grid
y_origin: 0

# --- Diagnostics --------------------------------------------------------------
# simulated hydrologic fluxes
OUTPUT_RATE:
- "prec"
- "aet"  # actual evapotranspiration (mm/day)
- "transp"  # transpiration (mm/day)
- "evap_soil"  # soil evaporation (mm/day)
- "inf_mat_rz"  # soil matrix infiltration into root zone (mm/day)
- "inf_mp_rz"  # macropore infiltration into root zone (mm/day)
- "inf_sc_rz"  # shrinkage crack infiltration into root zone (mm/day)
- "inf_ss"  # infiltration into subsoil (mm/day)
- "q_rz"  # percolation from root zone (mm/day)
- "q_ss"  # percolation from subsoil (mm/day)
- "q_sub"  # lateral subsurface runoff (mm/day)
- "cpr_rz" # capillary rise from subsoil into root zone (mm/day)
- "dS"  # change of storage volume (mm/day)
- "q_snow"  # snow melt (mm/day)

# simulated hydrologic storages
OUTPUT_COLLECT:
- "S_rz"  # storage volume of root zone (mm)
- "S_ss"  # storage volume of subsoil (mm)
- "theta_rz"  # soil water content of root zone (-)
- "theta_ss"  # soil water content of subsoil (-)
- "theta"  # soil water content (-)
- "S_snow"  # storage volume snow cover (mm)
