# --- Parameters ---------------------------------------------------------------
# land use ID (see README for description)
LU_ID: 8
# degree of sealing (-)
SEALING: 0
# total surface depression storage (mm)
S_DEP_TOT: 0
# soil depth (mm)
Z_SOIL: 1000
# density of vertical macropores (1/m2)
DMPV: 50
# total length of vertical macropores (mm)
LMPV: 500
# air capacity (-)
THETA_AC: 0.1
# usable field capacity (-)
THETA_UFC: 0.1
# permanent wilting point (-)
THETA_PWP: 0.2
# saturated hydraulic conductivity (-)
KS: 9.2
# hydraulic conductivity of bedrock/saturated zone (-)
KF: 2500

# --- Initial conditions -------------------------------------------------------
# soil water content of root zone/upper soil layer (mm/h)
THETA_RZ: 0.3
# soil water content of subsoil/lower soil layer (mm/h)
THETA_SS: 0.3

# --- Diagnostics --------------------------------------------------------------
# simulated hydrologic fluxes
OUTPUT_RATE:
- "prec"
- "aet"
- "transp"
- "evap_soil"
- "inf_mat_rz"
- "inf_mp_rz"
- "inf_sc_rz"
- "inf_ss"
- "q_rz"
- "q_ss"
- "cpr_rz"
- "dS"
- "q_snow"

# simulated hydrologic storages
OUTPUT_COLLECT:
- "S_rz"
- "S_ss"
- "S_pwp_rz"
- "S_fc_rz"
- "S_sat_rz"
- "S_pwp_ss"
- "S_fc_ss"
- "S_sat_ss"
- "theta_rz"
- "theta_ss"
- "theta"
- "S_snow"
