# --- Settings -----------------------------------------------------------------

# --- Grid ---------------------------------------------------------------------

# --- Parameters ---------------------------------------------------------------
# land use ID (see README for description)
LU_ID: 8
# degree of sealing (-)
SEALING: 0
# total surface depression storage (mm)
S_DEP_TOT: 0
# soil depth (mm)
Z_SOIL: 1000
# density of vertical macropores (1/m2)
DMPV: 50
# total length of vertical macropores (mm)
LMPV: 300
# air capacity (-)
THETA_AC: 0.08
# usable field capacity (-)
THETA_UFC: 0.15
# permanent wilting point (-)
THETA_PWP: 0.17
# saturated hydraulic conductivity (-)
KS: 9.2
# hydraulic conductivity of bedrock/saturated zone (-)
KF: 5

# --- Initial conditions -------------------------------------------------------
# soil water content of root zone/upper soil layer (-)
THETA_RZ: 0.32
# soil water content of subsoil/lower soil layer (-)
THETA_SS: 0.32

# --- Forcing ------------------------------------------------------------------

# --- Diagnostics --------------------------------------------------------------
# simulated hydrologic fluxes
output_fluxes:
- "inf_mat"
- "inf_mp"
- "inf_sc"
- "q_ss"
- "q_hof"
- "q_sof"

# simulated hydrologic storages
output_storages:
- "theta"
