# --- Parameters ---------------------------------------------------------------
SAS_SOLVER: 'deterministic'
TRANSPORT_MODEL_STRUCTURE: 'power'

# --- Initial conditions -------------------------------------------------------
# initial oxygen18 ration ofsoil water in root zone/upper soil layer (-)
d18O_RZ: -10
# initial oxygen18 ration ofsoil water in subsoil/lower soil layer (-)
d18O_SS: -10

# --- Diagnostics --------------------------------------------------------------
OUTPUT_AVERAGE:
- "C_iso_in"
- "C_iso_transp"
- "C_iso_evap_soil"
- "C_iso_s"
- "C_iso_q_ss"
- "ttavg_transp"
- "tt10_transp"
- "tt50_transp"
- "tt90_transp"
- "ttavg_q_ss"
- "tt10_q_ss"
- "tt50_q_ss"
- "tt90_q_ss"
- "rtavg_s"
- "rt10_s"
- "rt50_s"
- "rt90_s"
