# --- Parameters ---------------------------------------------------------------
SAS_SOLVER: 'deterministic'
TRANSPORT_MODEL_STRUCTURE: 'advection-dispersion'

# --- Initial conditions -------------------------------------------------------
# initial oxygen18 ration ofsoil water in root zone/upper soil layer (-)
d18O_RZ: -10
# initial oxygen18 ration ofsoil water in subsoil/lower soil layer (-)
d18O_SS: -10

# --- Diagnostics --------------------------------------------------------------
OUTPUT_AVERAGE:
- "C_iso_in"
- "C_iso_transp"
- "C_iso_evap_soil"
- "C_iso_s"
- "C_iso_q_ss"
- "TT_transp"
- "TT_q_ss"
- "SA_s"
- "ttavg_transp"
- "tt25_transp"
- "tt50_transp"
- "tt75_transp"
- "ttavg_q_ss"
- "tt25_q_ss"
- "tt50_q_ss"
- "tt75_q_ss"
- "rtavg_s"
- "rt25_s"
- "rt50_s"
- "rt75_s"
