cell_width: 1
enable_bromide: false
enable_chloride: false
enable_crop_phenology: false
enable_crop_rotation: false
enable_deuterium: false
enable_film_flow: false
enable_groundwater: false
enable_groundwater_boundary: false
enable_lateral_flow: false
enable_nitrate: true
enable_offline_transport: true
enable_oxygen18: false
experiment_name: dummy
ncols: 1
nrows: 1
output_variables:
tm_structure: complete-mixing
