name: Tests

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    name: Run tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8", "3.9"]
        backend: [numpy, jax]

    env:
      PETSC_VERSION: 3.15
      PETSC_DIR: /home/runner/petsc
      PETSC_ARCH: arch-linux-c-opt
      OMPI_MCA_rmaps_base_oversubscribe: "1"
      OMPI_MCA_mpi_yield_when_idle: "1"
      ROGER_REQUIRE_CYTHON_EXT: "1"

    steps:
      - uses: actions/checkout@v2

      # make sure tags are fetched so we can get a version
      - run: git fetch --prune --unshallow --tags

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore pip cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ matrix.os }}-pip-

      - name: Restore PETSc build cache
        uses: actions/cache@v2
        id: petsc-cache
        with:
          path: ${{ env.PETSC_DIR }}
          key: ${{ matrix.os }}-${{ env.PETSC_VERSION }}

      - name: Setup Python environment
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install cython

      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev

      - name: Build PETSc
        if: steps.petsc-cache.outputs.cache-hit != 'true'
        run: |
          git clone -b v$PETSC_VERSION --depth 1 https://gitlab.com/petsc/petsc.git $PETSC_DIR
          pushd $PETSC_DIR
          ./configure --with-debugging=0 -with-shared-libraries --with-precision=double
          make all
          popd

      - name: Install Roger
        run: |
          pip install mpi4py
          if [ ${{ matrix.backend }} == "jax" ]
          then
            pip install mpi4jax
            pip install -e .[test,jax]
          else
            pip install -e .[test]
          fi
          pip install petsc4py==$PETSC_VERSION --no-deps

      - name: Run tests
        run: |
          pytest . -v --cov --backend ${{ matrix.backend }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
