name: Test installation

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test-install:
    name: Test pip install

    defaults:
      run:
        shell: bash {0}

    strategy:
      fail-fast: false

      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version: ["3.9", "3.12"]
          nocc: [false]

          include:
            # also test whether installation without C compiler works
            - os: ubuntu-latest
              python-version: "3.9"
              nocc: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CUDA
        if: runner.os == 'Linux' && matrix.nocc != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install nvidia-cuda-toolkit

      - name: Test installing Roger
        run: |
          if ${{ matrix.nocc }}; then export CC=foobar; fi
          python -m pip install .
